// <auto-generated />
using System;
using LibPort.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibPort.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibPort.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d14feee2-e37d-471f-9eda-7ce87977fd78"),
                            Author = "Luigi Cash",
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acute tonsillitis",
                            Quantity = 1,
                            Title = "Cast a Dark Shadow (Angel)",
                            Total = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f34d64ed-786d-4035-8da5-436979306744"),
                            Author = "Crystie Delgadillo",
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hypermobility of coccyx",
                            Quantity = 2,
                            Title = "Never Too Young to Die",
                            Total = 2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("af4ff5db-9c95-4904-8261-826a3cc4db0d"),
                            Author = "Blair Galvis",
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Separation of muscle (nontraumatic)",
                            Quantity = 3,
                            Title = "Free Zone",
                            Total = 3,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("636f189e-3c66-4b81-99c2-5efb858adf4e"),
                            Author = "Jarrett Leasure",
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dysplasia of vagina",
                            Quantity = 4,
                            Title = "Disaster Zone: Volcano in New York",
                            Total = 4,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d0069c60-1bb3-49f3-8307-bd5ed4a50544"),
                            Author = "Myrtis Reinhard",
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chronic periodontitis",
                            Quantity = 5,
                            Title = "Salting the Battlefield",
                            Total = 5,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a55f0c23-b173-4ce5-a67d-9d2630597e7e"),
                            Author = "Sharie Giauque",
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gonococcal infection of lower genitourinary tract",
                            Quantity = 6,
                            Title = "Book of Life, The",
                            Total = 6,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("15ae6a7e-93b5-4e60-8a3c-328c06f2094e"),
                            Author = "Ramonita Hatzell",
                            CategoryId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acute osteomyelitis",
                            Quantity = 7,
                            Title = "Bossa Nova",
                            Total = 7,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7b75b12d-3dc4-465a-ae54-bcd0fe2dc57a"),
                            Author = "Eddy Marney",
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enthesopathy of hip region",
                            Quantity = 8,
                            Title = "Police Story",
                            Total = 8,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9cfc33e9-fd14-4d4d-9bb9-4cfd1405a2b9"),
                            Author = "Santo Ashbrook",
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Salter-Harris Type III physeal fracture of lower end of radius",
                            Quantity = 9,
                            Title = "Other Side of the Bed, The (Lado de la cama, El)",
                            Total = 9,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6a2ecb2f-ec0b-4e27-b6f8-f8f9842ce4a2"),
                            Author = "Rebeca Mcsherry",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gout, unspecified",
                            Quantity = 10,
                            Title = "Inside Job",
                            Total = 10,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c8660f77-c183-4f8c-8f99-6e8b7c55cc06"),
                            Author = "Wilfred Paquin",
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Burn of unspecified degree",
                            Quantity = 1,
                            Title = "Moloch",
                            Total = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("eaf263b6-cb6a-40b6-a490-81e37437f923"),
                            Author = "Devin Bramwell",
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Venous complication",
                            Quantity = 2,
                            Title = "Lego Star Wars: The Empire Strikes Out",
                            Total = 2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0d60e77e-d9a6-4d47-84b2-7058b265b963"),
                            Author = "Florencio Lackey",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nontraumatic rupture of muscle",
                            Quantity = 3,
                            Title = "Man Called Peter, A",
                            Total = 3,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9c961726-f1d0-41f3-8c42-e8aa36b2fc1c"),
                            Author = "Antwan Hewins",
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dystrophy of retina",
                            Quantity = 4,
                            Title = "Grumpier Old Men",
                            Total = 4,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("12b4719a-14f7-490f-b5d5-19104de89ff9"),
                            Author = "Lanny Florez",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Secondary malignant neoplasm of bone",
                            Quantity = 5,
                            Title = "Sunset Park",
                            Total = 5,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5083e315-fba5-4c27-8a24-6f574d3563ce"),
                            Author = "Laurence Dinsmore",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Anxiety disorder",
                            Quantity = 6,
                            Title = "Rainbow Thief, The",
                            Total = 6,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("14b35443-c5cc-44bb-9823-12ff1eaee847"),
                            Author = "Jaimee Gandara",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intestinal volvulus",
                            Quantity = 7,
                            Title = "Parallax View, The",
                            Total = 7,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fc994b85-01e0-4660-96f3-c7cf75b59e02"),
                            Author = "Cortney Mellen",
                            CategoryId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Preterm labor",
                            Quantity = 8,
                            Title = "Joy Ride 2: Dead Ahead",
                            Total = 8,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9c57b070-22f4-4d6f-97c4-3ac3a1bd6cc7"),
                            Author = "Maris Burgett",
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heatstroke",
                            Quantity = 9,
                            Title = "Phantom, The",
                            Total = 9,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2abbdca7-df70-498c-97ed-2c78d1a24fcb"),
                            Author = "Tami Daignault",
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Postoperative infection",
                            Quantity = 10,
                            Title = "Samantha: An American Girl Holiday",
                            Total = 10,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d0afd1e5-57b3-4694-9fba-b2b9db4f1474"),
                            Author = "Clyde Plak",
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All-in-one kit for making delicious chicken salad.",
                            Quantity = 1,
                            Title = "Séraphine",
                            Total = 1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("23d06134-f7b7-498f-9140-7226f97429de"),
                            Author = "Lulita Littlepage",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reusable silicone lids for covering food in bowls and storage containers.",
                            Quantity = 2,
                            Title = "How Do You Know",
                            Total = 2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("81403f89-497f-4195-8fdb-1a563a26a749"),
                            Author = "Josh Ivanenko",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deliciously smoked salmon, great for bagels.",
                            Quantity = 3,
                            Title = "Maria's Lovers",
                            Total = 3,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d4ab2ecc-609a-4519-8dbb-eeb969939b5f"),
                            Author = "Hale Stuchburie",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft and strong toilet paper for everyday use.",
                            Quantity = 4,
                            Title = "Aces: Iron Eagle III",
                            Total = 4,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e4c7412e-dc26-4428-87f8-2f79bc69cdea"),
                            Author = "Jackie Pavitt",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tender riblets coated in a honey barbecue glaze, perfect for grilling or baking.",
                            Quantity = 5,
                            Title = "Suzhou River (Suzhou he)",
                            Total = 5,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4eb50b68-0697-414b-a8b5-d96132d536cf"),
                            Author = "Leslie Gloy",
                            CategoryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Professional sharpening system for kitchen knives.",
                            Quantity = 6,
                            Title = "Bullitt",
                            Total = 6,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ee1e1fca-1536-4458-9699-56c4055418ee"),
                            Author = "Maureene Paragreen",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Natural pink salt, perfect for seasoning.",
                            Quantity = 7,
                            Title = "Amen.",
                            Total = 7,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("05b596de-000f-4640-868a-f7ce351fca72"),
                            Author = "Georgianne Seeds",
                            CategoryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gluten-free bread mix made with almond flour.",
                            Quantity = 8,
                            Title = "Klip (Clip)",
                            Total = 8,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("da9302d2-2899-473e-aa12-89d8fa200901"),
                            Author = "Bink Smithies",
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ready-to-eat salad with kale, lemon, and cheese.",
                            Quantity = 9,
                            Title = "Is the Man Who Is Tall Happy?",
                            Total = 9,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("13622935-03ef-471d-967a-425b7ee8ade6"),
                            Author = "Idalia Erskin",
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Small toolkit with essentials for home repairs.",
                            Quantity = 10,
                            Title = "New Rose Hotel",
                            Total = 10,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("02809c89-bd9f-4248-9037-c7dac59bce94"),
                            Author = "Jemimah Wilsey",
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hands-free waist pack for carrying essentials while walking your dog.",
                            Quantity = 11,
                            Title = "The Borderlands",
                            Total = 11,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cbc3779c-f158-4543-b6f3-6872576035fc"),
                            Author = "Gilda Labet",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Anti-fog ski goggles for winter sports.",
                            Quantity = 12,
                            Title = "War on Democracy, The",
                            Total = 12,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b5158d69-a32c-4f77-a15e-0deeb715a422"),
                            Author = "Frans Rames",
                            CategoryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Frozen shrimp seasoned with chili and lime, perfect for quick dinners.",
                            Quantity = 13,
                            Title = "Mother's Courage: Talking Back to Autism, A",
                            Total = 13,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1aac33d9-836e-4217-8a80-6d3adb072d71"),
                            Author = "Fionnula Readshall",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oven-roasted potatoes tossed in garlic and parmesan cheese seasoning.",
                            Quantity = 14,
                            Title = "Persepolis",
                            Total = 14,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e0cf2ddf-4568-49e8-b3ba-c717a89d03d1"),
                            Author = "Laura Rabjohn",
                            CategoryId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact laundry bag for travel use.",
                            Quantity = 15,
                            Title = "Follow the Bitch",
                            Total = 15,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cd7ac5fd-0fc3-493d-8e97-d6f239b6897c"),
                            Author = "Stormy Latta",
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HEPA air purifier for clean indoor air.",
                            Quantity = 16,
                            Title = "Puppet Master",
                            Total = 16,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00d358c7-ab98-4273-b4c3-3c672cec527d"),
                            Author = "Lolita Worpole",
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact and portable backpack for day trips and travel.",
                            Quantity = 17,
                            Title = "Meatballs III",
                            Total = 17,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3036a334-da9b-444e-b56b-45df1fbfa7b4"),
                            Author = "Gerrard Abramsky",
                            CategoryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Infuser for brewing loose-leaf herbal teas easily.",
                            Quantity = 18,
                            Title = "Righteous Kill",
                            Total = 18,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c5dfdaea-a696-40f0-8383-35892e5d396c"),
                            Author = "Yolanda Duncanson",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Juicy and tender beef sirloin steak, grass-fed.",
                            Quantity = 19,
                            Title = "The Vengeance of Fu Manchu",
                            Total = 19,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("acb3b5d0-4f5b-49a8-8b7c-0f175cbf41a1"),
                            Author = "Terrence Petry",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sweet popcorn coated in a mixture of cinnamon and sugar.",
                            Quantity = 20,
                            Title = "Generation War",
                            Total = 20,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("af8a666f-0167-4d2b-8672-ff5acf49091a"),
                            Author = "Viviene Klimas",
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A fresh salad made with black beans, corn, and a zesty dressing, great for summer cookouts.",
                            Quantity = 21,
                            Title = "Mad Love (Sappho)",
                            Total = 21,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a97f2ee1-9f04-43de-bd5c-7a4df9ecaf86"),
                            Author = "Rosamond Daveran",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fun book filled with puzzles and games for kids.",
                            Quantity = 22,
                            Title = "Get Over It",
                            Total = 22,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("562ea69d-8995-45be-9d07-d1149919e526"),
                            Author = "Freddy Lacroix",
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rechargeable LED camping lantern for outdoor use.",
                            Quantity = 23,
                            Title = "Escape from Dartmoor",
                            Total = 23,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f1aae3fd-482c-4bf4-a940-e3e15780806f"),
                            Author = "Fredek Adamowitz",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elevate your outfit with this sophisticated velvet blazer.",
                            Quantity = 24,
                            Title = "Racing Stripes",
                            Total = 24,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8d2c9032-539f-4f63-959b-feec2204ae57"),
                            Author = "Nicola Decayette",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fresh and zesty salsa, perfect for nachos.",
                            Quantity = 25,
                            Title = "Operation Homecoming: Writing the Wartime Experience",
                            Total = 25,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fb6cfc75-fa54-4c30-8d56-91608969484c"),
                            Author = "Bunny Wapplington",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crispy chicken bites, perfect for dipping.",
                            Quantity = 26,
                            Title = "In Secret",
                            Total = 26,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f66730ac-1d29-4f4b-9718-0c5045426a09"),
                            Author = "Minne Baradel",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Frozen pizza loaded with fresh vegetables and mozzarella cheese.",
                            Quantity = 27,
                            Title = "Necessary Roughness",
                            Total = 27,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d034954b-f61a-4926-b9c9-f3a4b0e4f626"),
                            Author = "Valentijn Charity",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crispy chicken nuggets for quick meals.",
                            Quantity = 28,
                            Title = "Aviator's Wife, The (La femme de l'aviateur)",
                            Total = 28,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c2a904cc-83c2-46a7-8466-7cebb500420b"),
                            Author = "Giffie Bonsale",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mix to create a delicious chia seed pudding in just a few minutes.",
                            Quantity = 29,
                            Title = "It's Good to Be Alive",
                            Total = 29,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1ab9093-d731-46e7-b682-d8a524256153"),
                            Author = "Phedra Dumingos",
                            CategoryId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A mix of grilled vegetables, ready to heat for quick side dishes.",
                            Quantity = 30,
                            Title = "Strange Cargo",
                            Total = 30,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2e027286-404b-4030-adb5-32b0b1627207"),
                            Author = "Doralia Knowling",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact organizer for cosmetics during travel.",
                            Quantity = 31,
                            Title = "Viva Las Vegas",
                            Total = 31,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a2a29509-076a-49ca-8552-f65e1eb00384"),
                            Author = "Murray Dubery",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sweet mixture of cinnamon and sugar for sprinkling.",
                            Quantity = 32,
                            Title = "Weddings and Babies ",
                            Total = 32,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8e15def4-c718-4c7d-bd97-82873a02d398"),
                            Author = "Cecilius Rein",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Frozen mix of colorful stir-fry veggies.",
                            Quantity = 33,
                            Title = "Faust",
                            Total = 33,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("94531835-1b96-4804-97a8-13cdb33be870"),
                            Author = "Jaynell Nutton",
                            CategoryId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Light and crispy baked chips, a healthier snack option.",
                            Quantity = 34,
                            Title = "Business of Fancydancing, The",
                            Total = 34,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("99fa40dc-076c-4f54-931d-e7fe77385f41"),
                            Author = "Jasun Crapper",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quick and easy rice pilaf mix for side dishes.",
                            Quantity = 35,
                            Title = "Edge of Seventeen",
                            Total = 35,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("58fc28e6-4a55-4d1b-b54f-739bef68f838"),
                            Author = "Clay Loker",
                            CategoryId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crispy and crunchy snack made from assorted vegetables.",
                            Quantity = 36,
                            Title = "Pépé le Moko",
                            Total = 36,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e5ffb3e2-35fb-4e65-b9e3-ee542a454c8b"),
                            Author = "Kora Rosenthaler",
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Freshly baked rustic bread, perfect for sandwiches or dipping in olive oil.",
                            Quantity = 37,
                            Title = "Beer League",
                            Total = 37,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c024c7ef-b7f0-4fa0-abf8-ecc5f51e0cc0"),
                            Author = "Umberto Fagan",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rich and creamy tomato basil soup, perfect with a grilled cheese.",
                            Quantity = 38,
                            Title = "Girl Model",
                            Total = 38,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e67ad3cc-0049-4576-8e5f-58a5f0c49776"),
                            Author = "Jacquelin McAvinchey",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft cotton pajama set for cozy nights in.",
                            Quantity = 39,
                            Title = "Yolki",
                            Total = 39,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bb9b0f9d-990e-4a67-ab59-668b23d9a9a6"),
                            Author = "Leonid Patten",
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trendy leggings with a unique graphic print, versatile for workouts and casual wear.",
                            Quantity = 40,
                            Title = "Model Couple, The (Le couple témoin)",
                            Total = 40,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8873bb31-91d2-4fb9-befc-ee186bb78d23"),
                            Author = "Annalee Oakenfield",
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight hair dryer with multiple speed settings.",
                            Quantity = 41,
                            Title = "Adventure of Sherlock Holmes' Smarter Brother, The",
                            Total = 41,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d7874d05-2e51-4da4-9217-0caa7f107561"),
                            Author = "Inness Brenton",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reusable tote bags for shopping and eco-friendly living.",
                            Quantity = 42,
                            Title = "Room 237",
                            Total = 42,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5719b541-9fe4-4230-8491-b2bac997f22c"),
                            Author = "Georgine Pedel",
                            CategoryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Programmable pet feeder for scheduled meals.",
                            Quantity = 43,
                            Title = "Angst",
                            Total = 43,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("402a2e5e-1186-4c37-9ae6-f448e3f06a40"),
                            Author = "Ingaborg Limb",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crispy spring rolls filled with vegetables",
                            Quantity = 44,
                            Title = "Backwood Philosopher (Havukka-ahon ajattelija)",
                            Total = 44,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b4f1278c-45f8-4950-a77e-e8cfbd993abf"),
                            Author = "Lauraine Coucher",
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete sculpting tools for artists.",
                            Quantity = 45,
                            Title = "Wholly Moses",
                            Total = 45,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("60eefe1a-0cab-4cdf-b15c-9d96d142d921"),
                            Author = "Timoteo Jeannel",
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Advanced electric toothbrush for effective cleaning.",
                            Quantity = 46,
                            Title = "American Psycho",
                            Total = 46,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4e06bbd1-6b56-410b-a325-f96ecf5f0f8a"),
                            Author = "Clarance Omand",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A pack of assorted nut and protein bars for a quick energy boost.",
                            Quantity = 47,
                            Title = "Murder in the First",
                            Total = 47,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fc8be6bc-08f3-45d0-b38f-38828baf7985"),
                            Author = "Loydie Glewe",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stylish wine rack to store and display bottles.",
                            Quantity = 48,
                            Title = "Meet Me at the Fair",
                            Total = 48,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3af945dc-3b18-4d41-a856-eb92fa59eb80"),
                            Author = "Lucila Tilburn",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Safety vest for pets during nighttime walks.",
                            Quantity = 49,
                            Title = "Hell Is for Heroes",
                            Total = 49,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f4d51cd9-3980-40a4-a364-5a6dc4d59acf"),
                            Author = "Alleen de Najera",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Professional-grade nail care set for manicures and pedicures.",
                            Quantity = 50,
                            Title = "Ballet Shoes",
                            Total = 50,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8818a00c-cbe3-4f4b-a106-7b9455b63860"),
                            Author = "Nadeen Kincaid",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stay dry with these stylish waterproof rain boots.",
                            Quantity = 51,
                            Title = "Time and Tide (Seunlau Ngaklau)",
                            Total = 51,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("87cc034c-af7a-4aa0-81c1-24077e4847c1"),
                            Author = "Nelia Kender",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Concentrated tomato paste, great for sauces.",
                            Quantity = 52,
                            Title = "Gold",
                            Total = 52,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e685bbb4-9f8f-4eb1-9874-a4306773bb32"),
                            Author = "Syd MacAloren",
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sweet peach halves packed in juice, great for desserts.",
                            Quantity = 53,
                            Title = "Resident Evil",
                            Total = 53,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1fcb574e-673f-4673-9bb7-2a57f630b220"),
                            Author = "Esme Harsant",
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Creamy tahini made from ground sesame seeds.",
                            Quantity = 54,
                            Title = "New Daughter, The",
                            Total = 54,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ab5e31da-7799-4778-a4e0-62db9b98600a"),
                            Author = "Collie Monini",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flexible tray for easy-release ice cubes.",
                            Quantity = 55,
                            Title = "Code, The",
                            Total = 55,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a3794d6e-9532-4950-8965-8189868562ef"),
                            Author = "Amalea Sidden",
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nutritious and hearty pasta made from whole wheat flour.",
                            Quantity = 56,
                            Title = "Personals, The (Zheng hun qi shi)",
                            Total = 56,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2aa246b3-7e77-4e9c-bf1e-4e948a741000"),
                            Author = "Herc McGaffey",
                            CategoryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Convenient charging stand for smartphones and devices.",
                            Quantity = 57,
                            Title = "Small Town, The (a.k.a. The Town) (Kasaba)",
                            Total = 57,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ca4db238-ca7e-447a-b169-37a6e3f33296"),
                            Author = "Hyacinthie Blizard",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Qi-certified charger for fast wireless charging of smartphones.",
                            Quantity = 58,
                            Title = "The Story of Robin Hood and His Merrie Men",
                            Total = 58,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d81c58f8-c26f-4cb2-9ebf-0043cd6fbfdb"),
                            Author = "Benedikta Tinmouth",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ready-to-bake garlic breadsticks, perfect with pasta dishes.",
                            Quantity = 59,
                            Title = "Maniac",
                            Total = 59,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("170f7afa-c2df-42df-b4a9-4f522d4ccab8"),
                            Author = "Beverley Lambal",
                            CategoryId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wi-Fi camera with motion detection for home security.",
                            Quantity = 60,
                            Title = "Bad Company",
                            Total = 60,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("677485a2-2823-4d97-a72b-d547f5db552e"),
                            Author = "Josee Iacovucci",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rechargeable LED lantern ideal for camping and outdoor activities.",
                            Quantity = 61,
                            Title = "Flirtation Walk",
                            Total = 61,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("90ec31c5-e5fa-4cef-adf9-ca2ad65896b0"),
                            Author = "Isidro Petkovic",
                            CategoryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomically designed pillow with breathable bamboo cover.",
                            Quantity = 62,
                            Title = "My Louisiana Sky",
                            Total = 62,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f7b64763-6d93-4ffd-a43e-96aa5e20a1d2"),
                            Author = "Ezmeralda O'Hone",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adjustable weighted jump rope for workouts.",
                            Quantity = 63,
                            Title = "Grudge 3, The",
                            Total = 63,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c7223325-3b1a-4175-964d-9ff61d7a485f"),
                            Author = "Elenore Bonnavant",
                            CategoryId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A convenient meal kit for making a delicious beef taco skillet at home.",
                            Quantity = 64,
                            Title = "Bite the Bullet",
                            Total = 64,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c8243167-8e15-4196-9ccd-b002874aca44"),
                            Author = "Janeen Durnford",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crisp and delicious organic apples.",
                            Quantity = 65,
                            Title = "Sarah Silverman:  We Are Miracles",
                            Total = 65,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4029dd19-9027-4b8d-9646-07547c162193"),
                            Author = "Francene Marriot",
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Moist brownie topped with sea salt and caramel drizzle.",
                            Quantity = 66,
                            Title = "Bounce: Behind the Velvet Rope",
                            Total = 66,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d66da54f-abc3-4094-9abc-d2bd304d3f3c"),
                            Author = "Laure Jugging",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stay hydrated with refreshing flavored water.",
                            Quantity = 67,
                            Title = "On the Edge (Hak bak do)",
                            Total = 67,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d72a788f-dc57-492a-b62f-f268557dc96c"),
                            Author = "Dierdre Howey",
                            CategoryId = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multi-functional grater for cheese and vegetables.",
                            Quantity = 68,
                            Title = "Shadow People",
                            Total = 68,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("51e3d063-2c80-416e-b4ae-836a3b4ab56f"),
                            Author = "Justus Farran",
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gentle brush for removing loose fur from pets.",
                            Quantity = 69,
                            Title = "Direct Contact",
                            Total = 69,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8983ec49-ef9f-419d-88f0-fea619bc1bd2"),
                            Author = "Brande Pellew",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comprehensive first aid kit for home or travel emergencies.",
                            Quantity = 70,
                            Title = "Taxi to the Dark Side",
                            Total = 70,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bc0f2ed8-171a-4155-ae4d-f33dd82727f0"),
                            Author = "Kaiser Greggs",
                            CategoryId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Brews coffee with a smooth flavor without bitterness.",
                            Quantity = 71,
                            Title = "Three Seasons",
                            Total = 71,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("aaa3b385-032e-408f-8f9d-ae8e04d66596"),
                            Author = "Octavius Ibotson",
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Space-saving cup that folds flat for easy storage.",
                            Quantity = 72,
                            Title = "As Good as Dead",
                            Total = 72,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1ae97f4c-1003-4923-bd8b-86230e819310"),
                            Author = "Heindrick Walcot",
                            CategoryId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Frozen zucchini slices coated in parmesan cheese, perfect for baking or frying.",
                            Quantity = 73,
                            Title = "Beautiful Girls",
                            Total = 73,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("472d00c2-c68e-4003-a266-4cf0bc1d6df9"),
                            Author = "Rudyard Egdal",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Frozen sausage patties made with herbs and spices, perfect for breakfast sandwiches.",
                            Quantity = 74,
                            Title = "Kim",
                            Total = 74,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("80c888ba-4de4-4b69-a870-d97a2c05221c"),
                            Author = "Celia Robjohns",
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crunchy pretzels dipped in rich dark chocolate.",
                            Quantity = 75,
                            Title = "Last Metro, The (Dernier métro, Le)",
                            Total = 75,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4640b125-c365-45e4-a8eb-2f4121aadd9e"),
                            Author = "Irita Lomasny",
                            CategoryId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crunchy seeds perfect for toppings and baking.",
                            Quantity = 76,
                            Title = "Men with Guns",
                            Total = 76,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bb10f212-c412-4da4-9e01-54dff7217207"),
                            Author = "Judah Handlin",
                            CategoryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Set of reusable stainless steel straws for drinks.",
                            Quantity = 77,
                            Title = "Ju-on: The Grudge 2",
                            Total = 77,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ef366006-b902-479b-a54b-3b711c8c64fc"),
                            Author = "Goldia Siddens",
                            CategoryId = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Farm fresh eggs, essential for breakfast.",
                            Quantity = 78,
                            Title = "Iceman",
                            Total = 78,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ac795052-aaf9-41c4-92f5-44056b425c5f"),
                            Author = "Eachelle Bruckman",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A fashion-forward bomber jacket to elevate your casual looks.",
                            Quantity = 79,
                            Title = "Street Angel",
                            Total = 79,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("873878ae-4224-4737-aca6-576ea7a37c2a"),
                            Author = "Dan Effemy",
                            CategoryId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spreadable cream cheese with garlic and herbs.",
                            Quantity = 80,
                            Title = "The Oscar",
                            Total = 80,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0053ea56-f57f-4bdf-8cae-e55cdcaf843f"),
                            Author = "Christean Baldree",
                            CategoryId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soft and warm corn tortillas, perfect for tacos and burritos.",
                            Quantity = 81,
                            Title = "Celluloid Closet, The",
                            Total = 81,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8eb071ad-37b3-41db-a45d-9adbd7c46f29"),
                            Author = "Kamilah Easey",
                            CategoryId = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hands-on experience with science and engineering projects.",
                            Quantity = 82,
                            Title = "Little Girl Who Lives Down the Lane, The",
                            Total = 82,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LibPort.Models.BookBorrowingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequestorId");

                    b.ToTable("BookBorrowingRequests");
                });

            modelBuilder.Entity("LibPort.Models.BookBorrowingRequestDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("RequestId");

                    b.ToTable("BookBorrowingRequestDetails");
                });

            modelBuilder.Entity("LibPort.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Comedy",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Documentary",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Drama",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Romance",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Action",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fantasy",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Horror",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Crime",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mystery",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adventure",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Western",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Animation",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LibPort.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LibPort.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibPort.Models.Book", b =>
                {
                    b.HasOne("LibPort.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibPort.Models.BookBorrowingRequest", b =>
                {
                    b.HasOne("LibPort.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LibPort.Models.User", "Requestor")
                        .WithMany("BorrowingRequests")
                        .HasForeignKey("RequestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Requestor");
                });

            modelBuilder.Entity("LibPort.Models.BookBorrowingRequestDetails", b =>
                {
                    b.HasOne("LibPort.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibPort.Models.BookBorrowingRequest", "BookBorrowingRequest")
                        .WithMany("Details")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookBorrowingRequest");
                });

            modelBuilder.Entity("LibPort.Models.Review", b =>
                {
                    b.HasOne("LibPort.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibPort.Models.Book", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LibPort.Models.BookBorrowingRequest", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("LibPort.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibPort.Models.User", b =>
                {
                    b.Navigation("BorrowingRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
